name: release
on:
  push:
    paths:
      - "**"

jobs:
  release:
    name: timescaledb-metrics
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      run: go test -v ./...

    - name: Get RELEASE_TAG
      if: startsWith(github.ref, 'release')
      run: |
        echo ::set-env name=RELEASE_TAG::$(echo ${{ github.ref }} | rev | cut -d '/' -f1 | rev)

    - name: Build timescale metrics for linux x86_64
      if: startsWith(github.ref, 'release')
      run: env GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -ldflags="-X 'main.VERSION=v${{ env.RELEASE_TAG }}'" -o timescaledb_metrics_linux_x86_64 -installsuffix cgo github.com/last9/timescaledb-metrics/

    - name: Build timescale metrics for mac x86_64
      if: startsWith(github.ref, 'release')
      run: env GOOS=darwin GARCH=amd64 CGO_ENABLED=0 go build -ldflags="-X 'main.VERSION=v${{ env.RELEASE_TAG }}'" -o timescaledb_metrics_darwin_x86_64 -installsuffix cgo github.com/last9/timescaledb-metrics/

    - name: Get release
      if: startsWith(github.ref, 'release')
      id: get_release
      uses: bruceadams/get-release@v1.2.1
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload release asset for linux_x86_64
      if: startsWith(github.ref, 'release')
      id: upload-artifact-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./timescaledb_metrics_linux_x86_64
        asset_name: timescaledb_metrics_linux_x86_64
        asset_content_type: application/octet-stream

    - name: Upload release asset for darwin_x86_64
      if: startsWith(github.ref, 'release')
      id: upload-artifact-osx
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./timescaledb_metrics_darwin_x86_64
        asset_name: timescaledb_metrics_darwin_x86_64
        asset_content_type: application/octet-stream
